// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nkpYADXfkuIgeMJ3y_UcluF6wuNMPT0',
    appId: '1:360880078134:web:9fc558d9db398f77b44797',
    messagingSenderId: '360880078134',
    projectId: 'thequizofmid',
    authDomain: 'thequizofmid.firebaseapp.com',
    storageBucket: 'thequizofmid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuBTRIXCbQZiQ-n0pzNY766-YnP0VmbRw',
    appId: '1:360880078134:android:798e62ae61fccff9b44797',
    messagingSenderId: '360880078134',
    projectId: 'thequizofmid',
    storageBucket: 'thequizofmid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvXzCYBJ0iMLy3p8wVbHAGDgZcQJAscR4',
    appId: '1:360880078134:ios:aa8cc94d42da3746b44797',
    messagingSenderId: '360880078134',
    projectId: 'thequizofmid',
    storageBucket: 'thequizofmid.appspot.com',
    iosBundleId: 'com.example.theQuizAppMid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvXzCYBJ0iMLy3p8wVbHAGDgZcQJAscR4',
    appId: '1:360880078134:ios:84e87765990ab76eb44797',
    messagingSenderId: '360880078134',
    projectId: 'thequizofmid',
    storageBucket: 'thequizofmid.appspot.com',
    iosBundleId: 'com.example.theQuizAppMid.RunnerTests',
  );
}
